import type { Metadata } from "next"
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import "./globals.scss"
import { ThemeProvider } from "@/components/theme-provider"
import DefaultWrapper from "@/components/default-wrapper"
import { StartAnimation } from "@/components/animation/"

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
				<ThemeProvider attribute='class' defaultTheme='dark' enableSystem disableTransitionOnChange>
					<DefaultWrapper>{children}</DefaultWrapper>
				</ThemeProvider>
				{/* ANIMATIONS */}
				<StartAnimation />
			</body>
		</html>
	)
}
